apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeforge-frontend
  namespace: codeforge-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeforge-frontend
  template:
    metadata:
      labels:
        app: codeforge-frontend
    spec:
      containers:
        - name: codeforge-frontend
          image: ankit5609/codeforge-frontend@sha256:ae93bfcb1a4fa9d7d8256cba5de7804de2307619d4645fef7df653a86592567e
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: codeforge-frontend
  namespace: codeforge-core
spec:
  type: ClusterIP
  selector:
    app: codeforge-frontend
  ports:
    - port: 80
      targetPort: 80